export enum Icon {
  Armor = 'mdi-shield',
  Bullet = 'mdi-bullet',
  Name = 'mdi-lead-pencil',
  ArmorType = 'mdi-tshirt-crew',
  Penetration = 'svguse:penetration.svg#Layer_1',
  Damage = 'mdi-heart-broken',
  Boss = 'mdi-skull',
  MaxDurability = 'mdi-hammer-wrench',
  MoneyRubles = 'mdi-currency-rub',
  MoneyDollars = 'mdi-currency-usd',
  MoneyEuro = 'mdi-currency-eur',
  Map = 'mdi-map',
  MapMarker = 'mdi-map-marker-radius',
  Player = 'mdi-account',
  Playable = 'mdi-account-check',
  Health = 'mdi-hospital-box',
  Combatant = 'svguse:combatant.svg#Layer_1',
  Visible = 'mdi-eye',
  Invisible = 'mdi-eye-off',
  Back = 'mdi-arrow-left',
  Close = 'mdi-close',
  Death = 'mdi-skull-crossbones',
  Fee = 'mdi-bank',
  Human = 'mdi-human'
}